name: task6

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  mkdir 3rdparty
                  cd 3rdparty
                  git clone git@github.com:google/googletest.git
                  cd ..
                  mkdir build 
                  cd build 
                  cmake -DGOOGLE_TEST_DIR=googletest/ ..
                  make 
                  cd ..
