name: task6

on: [ push ]

env:
    GOOGLE_TEST_DIR: ${{ 'googletest/' }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  cd task6
                  mkdir 3rdparty
                  cd 3rdparty
                  git clone https://github.com/google/googletest.git
                  cd ..
                  mkdir build 
                  cd build 
                  cmake ..
                  make 
                  cd ../..

            - name: Test
              uses: akhtyamovpavel/ActionGtestReport@v0.0.9
              with:
                  exec-path: bin/CTestExe
                  report-path: report.xml
                  working-directory: task6/

            - name: UploadArtifacts
              uses: actions/upload-artifacts@v2
              with: 
                  name: Distributive
                  path: | 
                        ./task6/bin 
                        ./task6/lib
